# application configuration

application.name: 'example-app'
info.app:
  version: '3.0.0'
  description: 'Composable application example'

# server port for Event API REST endpoint
server.port: 8086

# log.format can be 'text' or 'json'
log:
  format: 'text'
  level: INFO

# You can add optional health checks that point to your custom health check functions
# (the dependency list is a comma separated list) 
health.dependencies: 'demo.health'

#
# Extension to MIME type mapping for static content
#
# By default, the system supports the following:
# js: application/json
# html: text/html
# htm: text/html
# txt: text/plain
# css: text/css
#
# any other extensions are served as application/octet-stream
#
# To support additional file extensions, please add the mapping in the mime.types section.
#
mime.types:
  xml: 'application/xml'
  woff2: 'font/woff2'
