# application configuration

application.name: 'example-app'
info.app:
  version: '3.0.0'
  description: 'Composable application example'

# server port for Event API REST endpoint
server.port: 8085

# log.format can be 'text' or 'json'
log:
  format: 'text'
  level: INFO

# You can add optional health checks that point to your custom health check functions
# (the dependency list is a comma separated list) 
health.dependencies: 'demo.health'
