# application configuration

application.name: 'example-app'
info.app:
  version: '3.0.0'
  description: 'Composable application example'

# server port for Event API REST endpoint
server.port: 8086

# log.format can be 'text' or 'json'
log:
  format: 'text'
  level: INFO

# You can add optional health checks that point to your custom health check functions
# (the dependency list is a comma separated list) 
health.dependencies: 'demo.health'

#
# Extension to MIME type mapping for static content
#
# By default, the system supports the following:
# js: application/json
# html: text/html
# htm: text/html
# txt: text/plain
# css: text/css
#
# Any other extensions are served as application/octet-stream
#
# To support additional file extensions, please update the mapping in the mime.types section here.
# You may want to limit the mime mapping to a bare minimal to fit your use case.
#
mime.types:
  ico: 'image/vnd.microsoft.icon'
  json: 'application/json'
  xml: 'application/xml'
  svg: 'image/svg+xml'
  svgz: 'image/svg+xml'
  sgi: image/sgi
  tiff: image/tiff
  tif: image/tiff
  jpeg: image/jpeg
  jpg: image/jpeg
  jpe: image/jpeg
  png: image/png
  ttc: font/collection
  otf: font/otf
  woff: 'font/woff'
  woff2: 'font/woff2'
  pdf: application/pdf
  doc: application/msword
